### ISSUE TITLE
Add Delete Announcement Button

### ISSUE THREAD

**Issue by menthy-wu** [acm-ucr/membership-portal-admin#22]
- In Announcement.js, add a trash can icon button at the bottom left of the pop-up to delete this announcement
![image](https://user-images.githubusercontent.com/73259022/215919476-fa7b08d6-0f32-41a2-8f90-f5958b272fe9.png)

**Comment by swooshoo** [comment]
@menthy-wu wouldn't it make more sense to include the delete annnouncement after you click 'edit' instead?

**Comment by menthy-wu** [comment]
it might be easier to use since you just need to click once instead of click twice
